[package]
name = "sanctum-misc-utils"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/igneous-labs/sanctum-solana-utils.git"

[dependencies]
borsh = { workspace = true }
solana-program = { workspace = true }
