[package]
name = "sanctum-solana-test-utils"
version = "0.1.0"
edition = "2021"

[features]
default = ["token"]
token = ["spl-token"]

[dependencies]
async-trait = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
solana-account-decoder = { workspace = true }
solana-program = { workspace = true }
solana-program-test = { workspace = true }
solana-readonly-account = { workspace = true, features = ["solana-sdk"] }
solana-sdk = { workspace = true }
spl-token = { workspace = true, optional = true }
